### ISSUE TITLE
FSDB.has() can't check whether level 1 key is exist in an empty database file

### ISSUE THREAD

**Issue by mazdel** [WillTDA/File-System-DB#1]
Hello, I'm really in love with this project. but I got an error when I need to check if my level 1 key exists or not (or in this project example is `player` key) in my empty database.
here is part of the error that I got
```
Debug: internal, implementation, error
SyntaxError: Unexpected end of JSON input 
at JSON.parse (<anonymous>)
at FSDB.get (/home/project/nodejs/submission/bookshelf-api/node_modules/file-system-db/index.js:123:25)
at FSDB.has (/home/project/nodejs/submission/bookshelf-api/node_modules/file-system-db/index.js:158:25)
at getAllBooks (/home/project/nodejs/submission/bookshelf-api/src/handler.js:81:10)
```

**Comment by WillTDA** [comment]
Hello 👋 Thank you for reaching out. An empty JSON database as far as FSDB is concerned looks like this:
```
{}
```
If your file contains absolutely nothing, then it is obvious that the package cannot parse data.

With that said, there are a number of checks in place to make sure that, if a file path specified in the `new FSDB()` constructor does not exist, it should be created. Before you run the `FSDB#has()` function:

- Run a `fs.existsSync()` on the file.
- Run a `fs.readFileSync` to check if the file contains anything at all.

If any of those checks show there is nothing there, recreate the FSDB instance, or set the file contents to `{}`.

If you have anything else to add, do not hesitate to reply back 😀

**Comment by mazdel** [comment]
with your explanation and some tests, I finally understand how this `FSDB` works for me. thanks for your response 😀
