### ISSUE TITLE
Add ES6 modules support

### ISSUE THREAD

**Issue by NewYanko** [WillTDA/File-System-DB#9]
hi - is this a planned feature?

i'm working with the `import`/`export` syntax in a project, and while [createRequire](https://nodejs.org/api/module.html#modulecreaterequirefilename) works fine, it comes at the cost of loosing intellisense from your jsdoc spec.

alternatively a `types` package would do the trick as well - thanks

**Comment by lewxdev** [comment]
@NewYanko That's my bad, the original v2.0.0 release didn't [indicate the type declaration file](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package) we compile on `prepublishOnly`. This should be resolved with #10 as soon as it's merged
